In [1]:
import numpy as np

In [2]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
for i in list_:
    print(f"{i} - {type(i)}")

1 - <class 'str'>
2 - <class 'str'>
3 - <class 'str'>
4 - <class 'str'>
5 - <class 'str'>


In [7]:
for i in array_list:
    print(f"{i} - {type(i)}")

1 - <class 'numpy.str_'>
2 - <class 'numpy.str_'>
3 - <class 'numpy.str_'>
4 - <class 'numpy.str_'>
5 - <class 'numpy.str_'>


In [8]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra list.

There will be a change in array_list elemets data type but, list_ elements data type remains unchanged.

In [9]:
for i in list_:
    print(f"{i} - {type(i)}")

1 - <class 'str'>
2 - <class 'str'>
3 - <class 'str'>
4 - <class 'str'>
5 - <class 'str'>


In [10]:
for i in array_list:
    print(f"{i} - {type(i)}")

1 - <class 'numpy.int64'>
2 - <class 'numpy.int64'>
3 - <class 'numpy.int64'>
4 - <class 'numpy.int64'>
5 - <class 'numpy.int64'>


In [11]:
import numpy as np
num_list = [[ 1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape (ii) size

In [14]:
num_array.shape

(2, 3)

In [15]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.fromfunction(lambda i, j: i*0,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])